[package]
name = "wallet_project_backend"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
